# Generated by Django 3.2.5 on 2021-11-12 15:15

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookModels',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title')),
                ('author', models.CharField(max_length=200, verbose_name='Autor')),
                ('pub_date', models.DateField(blank=True, null=True, verbose_name='Data publikacji')),
                ('nr_isbn_one', models.IntegerField(verbose_name='Pierwszy ISBN')),
                ('nr_isbn_two', models.IntegerField(blank=True, null=True, verbose_name='Drugi ISBN')),
                ('page_co', models.IntegerField(verbose_name='Ilość stron')),
                ('img_link', models.CharField(blank=True, max_length=200, null=True, verbose_name='Link do okładki')),
                ('pub_lang', models.CharField(max_length=20, verbose_name='Język publikacji')),
            ],
            options={
                'verbose_name': 'Książki',
                'verbose_name_plural': 'Dodaj książkę',
            },
        ),
    ]
